// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v5.29.3
// source: constraint.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConstraintType defines the type of constraint
type ConstraintType int32

const (
	ConstraintType_CONSTRAINT_TYPE_UNSPECIFIED    ConstraintType = 0
	ConstraintType_CONSTRAINT_TYPE_FIXED          ConstraintType = 1
	ConstraintType_CONSTRAINT_TYPE_MAX            ConstraintType = 2
	ConstraintType_CONSTRAINT_TYPE_MIN            ConstraintType = 3
	ConstraintType_CONSTRAINT_TYPE_RANGE          ConstraintType = 4
	ConstraintType_CONSTRAINT_TYPE_WHITELIST      ConstraintType = 5
	ConstraintType_CONSTRAINT_TYPE_MAX_PER_PERIOD ConstraintType = 6
	ConstraintType_CONSTRAINT_TYPE_MAGIC_CONSTANT ConstraintType = 7
)

// Enum value maps for ConstraintType.
var (
	ConstraintType_name = map[int32]string{
		0: "CONSTRAINT_TYPE_UNSPECIFIED",
		1: "CONSTRAINT_TYPE_FIXED",
		2: "CONSTRAINT_TYPE_MAX",
		3: "CONSTRAINT_TYPE_MIN",
		4: "CONSTRAINT_TYPE_RANGE",
		5: "CONSTRAINT_TYPE_WHITELIST",
		6: "CONSTRAINT_TYPE_MAX_PER_PERIOD",
		7: "CONSTRAINT_TYPE_MAGIC_CONSTANT",
	}
	ConstraintType_value = map[string]int32{
		"CONSTRAINT_TYPE_UNSPECIFIED":    0,
		"CONSTRAINT_TYPE_FIXED":          1,
		"CONSTRAINT_TYPE_MAX":            2,
		"CONSTRAINT_TYPE_MIN":            3,
		"CONSTRAINT_TYPE_RANGE":          4,
		"CONSTRAINT_TYPE_WHITELIST":      5,
		"CONSTRAINT_TYPE_MAX_PER_PERIOD": 6,
		"CONSTRAINT_TYPE_MAGIC_CONSTANT": 7,
	}
)

func (x ConstraintType) Enum() *ConstraintType {
	p := new(ConstraintType)
	*p = x
	return p
}

func (x ConstraintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintType) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[0].Descriptor()
}

func (ConstraintType) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[0]
}

func (x ConstraintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintType.Descriptor instead.
func (ConstraintType) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0}
}

type MagicConstant int32

const (
	MagicConstant_MAGIC_CONSTANT_UNSPECIFIED       MagicConstant = 0
	MagicConstant_MAGIC_CONSTANT_VULTISIG_TREASURY MagicConstant = 1
)

// Enum value maps for MagicConstant.
var (
	MagicConstant_name = map[int32]string{
		0: "MAGIC_CONSTANT_UNSPECIFIED",
		1: "MAGIC_CONSTANT_VULTISIG_TREASURY",
	}
	MagicConstant_value = map[string]int32{
		"MAGIC_CONSTANT_UNSPECIFIED":       0,
		"MAGIC_CONSTANT_VULTISIG_TREASURY": 1,
	}
)

func (x MagicConstant) Enum() *MagicConstant {
	p := new(MagicConstant)
	*p = x
	return p
}

func (x MagicConstant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MagicConstant) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[1].Descriptor()
}

func (MagicConstant) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[1]
}

func (x MagicConstant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MagicConstant.Descriptor instead.
func (MagicConstant) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{1}
}

// RangeValue represents a range constraint with min and max values
type RangeValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min string `protobuf:"bytes,1,opt,name=min,proto3" json:"min,omitempty"`
	Max string `protobuf:"bytes,2,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *RangeValue) Reset() {
	*x = RangeValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RangeValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RangeValue) ProtoMessage() {}

func (x *RangeValue) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RangeValue.ProtoReflect.Descriptor instead.
func (*RangeValue) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *RangeValue) GetMin() string {
	if x != nil {
		return x.Min
	}
	return ""
}

func (x *RangeValue) GetMax() string {
	if x != nil {
		return x.Max
	}
	return ""
}

// WhitelistValues represents a list of allowed values
type WhitelistValues struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Values []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
}

func (x *WhitelistValues) Reset() {
	*x = WhitelistValues{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WhitelistValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhitelistValues) ProtoMessage() {}

func (x *WhitelistValues) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhitelistValues.ProtoReflect.Descriptor instead.
func (*WhitelistValues) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{1}
}

func (x *WhitelistValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Constraint defines restrictions on a parameter
type Constraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Type of constraint (fixed, max, min, etc.)
	Type ConstraintType `protobuf:"varint,1,opt,name=type,proto3,enum=types.ConstraintType" json:"type,omitempty"`
	// Value of the constraint (depends on Type)
	//
	// Types that are assignable to Value:
	//
	//	*Constraint_FixedValue
	//	*Constraint_MaxValue
	//	*Constraint_MinValue
	//	*Constraint_RangeValue
	//	*Constraint_WhitelistValues
	//	*Constraint_MaxPerPeriodValue
	//	*Constraint_MagicConstantValue
	Value isConstraint_Value `protobuf_oneof:"value"`
	// Additional metadata for the constraint
	DenominatedIn string `protobuf:"bytes,9,opt,name=denominated_in,json=denominatedIn,proto3" json:"denominated_in,omitempty"`
	Period        string `protobuf:"bytes,10,opt,name=period,proto3" json:"period,omitempty"`
	Required      bool   `protobuf:"varint,11,opt,name=required,proto3" json:"required,omitempty"`
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_constraint_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{2}
}

func (x *Constraint) GetType() ConstraintType {
	if x != nil {
		return x.Type
	}
	return ConstraintType_CONSTRAINT_TYPE_UNSPECIFIED
}

func (m *Constraint) GetValue() isConstraint_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *Constraint) GetFixedValue() string {
	if x, ok := x.GetValue().(*Constraint_FixedValue); ok {
		return x.FixedValue
	}
	return ""
}

func (x *Constraint) GetMaxValue() string {
	if x, ok := x.GetValue().(*Constraint_MaxValue); ok {
		return x.MaxValue
	}
	return ""
}

func (x *Constraint) GetMinValue() string {
	if x, ok := x.GetValue().(*Constraint_MinValue); ok {
		return x.MinValue
	}
	return ""
}

func (x *Constraint) GetRangeValue() *RangeValue {
	if x, ok := x.GetValue().(*Constraint_RangeValue); ok {
		return x.RangeValue
	}
	return nil
}

func (x *Constraint) GetWhitelistValues() *WhitelistValues {
	if x, ok := x.GetValue().(*Constraint_WhitelistValues); ok {
		return x.WhitelistValues
	}
	return nil
}

func (x *Constraint) GetMaxPerPeriodValue() int32 {
	if x, ok := x.GetValue().(*Constraint_MaxPerPeriodValue); ok {
		return x.MaxPerPeriodValue
	}
	return 0
}

func (x *Constraint) GetMagicConstantValue() MagicConstant {
	if x, ok := x.GetValue().(*Constraint_MagicConstantValue); ok {
		return x.MagicConstantValue
	}
	return MagicConstant_MAGIC_CONSTANT_UNSPECIFIED
}

func (x *Constraint) GetDenominatedIn() string {
	if x != nil {
		return x.DenominatedIn
	}
	return ""
}

func (x *Constraint) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Constraint) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type isConstraint_Value interface {
	isConstraint_Value()
}

type Constraint_FixedValue struct {
	FixedValue string `protobuf:"bytes,2,opt,name=fixed_value,json=fixedValue,proto3,oneof"`
}

type Constraint_MaxValue struct {
	MaxValue string `protobuf:"bytes,3,opt,name=max_value,json=maxValue,proto3,oneof"`
}

type Constraint_MinValue struct {
	MinValue string `protobuf:"bytes,4,opt,name=min_value,json=minValue,proto3,oneof"`
}

type Constraint_RangeValue struct {
	RangeValue *RangeValue `protobuf:"bytes,5,opt,name=range_value,json=rangeValue,proto3,oneof"`
}

type Constraint_WhitelistValues struct {
	WhitelistValues *WhitelistValues `protobuf:"bytes,6,opt,name=whitelist_values,json=whitelistValues,proto3,oneof"`
}

type Constraint_MaxPerPeriodValue struct {
	MaxPerPeriodValue int32 `protobuf:"varint,7,opt,name=max_per_period_value,json=maxPerPeriodValue,proto3,oneof"`
}

type Constraint_MagicConstantValue struct {
	MagicConstantValue MagicConstant `protobuf:"varint,8,opt,name=magic_constant_value,json=magicConstantValue,proto3,enum=types.MagicConstant,oneof"`
}

func (*Constraint_FixedValue) isConstraint_Value() {}

func (*Constraint_MaxValue) isConstraint_Value() {}

func (*Constraint_MinValue) isConstraint_Value() {}

func (*Constraint_RangeValue) isConstraint_Value() {}

func (*Constraint_WhitelistValues) isConstraint_Value() {}

func (*Constraint_MaxPerPeriodValue) isConstraint_Value() {}

func (*Constraint_MagicConstantValue) isConstraint_Value() {}

var File_constraint_proto protoreflect.FileDescriptor

var file_constraint_proto_rawDesc = []byte{
	0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x0a, 0x52, 0x61, 0x6e,
	0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x69, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22, 0x29, 0x0a, 0x0f, 0x57,
	0x68, 0x69, 0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x22, 0xf4, 0x03, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x29, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x21, 0x0a, 0x0b, 0x66, 0x69, 0x78, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x69, 0x78, 0x65, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x12, 0x1d, 0x0a, 0x09, 0x6d, 0x69, 0x6e, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x08, 0x6d, 0x69, 0x6e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x34, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52,
	0x61, 0x6e, 0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x72, 0x61, 0x6e,
	0x67, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x43, 0x0a, 0x10, 0x77, 0x68, 0x69, 0x74, 0x65,
	0x6c, 0x69, 0x73, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x57, 0x68, 0x69, 0x74, 0x65, 0x6c,
	0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x48, 0x00, 0x52, 0x0f, 0x77, 0x68, 0x69,
	0x74, 0x65, 0x6c, 0x69, 0x73, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x12, 0x31, 0x0a, 0x14,
	0x6d, 0x61, 0x78, 0x5f, 0x70, 0x65, 0x72, 0x5f, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x11, 0x6d, 0x61,
	0x78, 0x50, 0x65, 0x72, 0x50, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x48, 0x0a, 0x14, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x12, 0x6d, 0x61, 0x67, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x73,
	0x74, 0x61, 0x6e, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x64, 0x65, 0x6e,
	0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x69, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x64, 0x65, 0x6e, 0x6f, 0x6d, 0x69, 0x6e, 0x61, 0x74, 0x65, 0x64, 0x49, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x70, 0x65, 0x72, 0x69, 0x6f, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x65, 0x71, 0x75,
	0x69, 0x72, 0x65, 0x64, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x2a, 0x80, 0x02,
	0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1f, 0x0a, 0x1b, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f, 0x54,
	0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x5f, 0x46, 0x49, 0x58, 0x45, 0x44, 0x10, 0x01, 0x12, 0x17, 0x0a, 0x13,
	0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4d, 0x41, 0x58, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x41,
	0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x49, 0x4e, 0x10, 0x03, 0x12, 0x19,
	0x0a, 0x15, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50,
	0x45, 0x5f, 0x52, 0x41, 0x4e, 0x47, 0x45, 0x10, 0x04, 0x12, 0x1d, 0x0a, 0x19, 0x43, 0x4f, 0x4e,
	0x53, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x57, 0x48, 0x49,
	0x54, 0x45, 0x4c, 0x49, 0x53, 0x54, 0x10, 0x05, 0x12, 0x22, 0x0a, 0x1e, 0x43, 0x4f, 0x4e, 0x53,
	0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41, 0x58, 0x5f,
	0x50, 0x45, 0x52, 0x5f, 0x50, 0x45, 0x52, 0x49, 0x4f, 0x44, 0x10, 0x06, 0x12, 0x22, 0x0a, 0x1e,
	0x43, 0x4f, 0x4e, 0x53, 0x54, 0x52, 0x41, 0x49, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x4d, 0x41, 0x47, 0x49, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x54, 0x41, 0x4e, 0x54, 0x10, 0x07,
	0x2a, 0x55, 0x0a, 0x0d, 0x4d, 0x61, 0x67, 0x69, 0x63, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x74, 0x12, 0x1e, 0x0a, 0x1a, 0x4d, 0x41, 0x47, 0x49, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x54,
	0x41, 0x4e, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10,
	0x00, 0x12, 0x24, 0x0a, 0x20, 0x4d, 0x41, 0x47, 0x49, 0x43, 0x5f, 0x43, 0x4f, 0x4e, 0x53, 0x54,
	0x41, 0x4e, 0x54, 0x5f, 0x56, 0x55, 0x4c, 0x54, 0x49, 0x53, 0x49, 0x47, 0x5f, 0x54, 0x52, 0x45,
	0x41, 0x53, 0x55, 0x52, 0x59, 0x10, 0x01, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_constraint_proto_rawDescOnce sync.Once
	file_constraint_proto_rawDescData = file_constraint_proto_rawDesc
)

func file_constraint_proto_rawDescGZIP() []byte {
	file_constraint_proto_rawDescOnce.Do(func() {
		file_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(file_constraint_proto_rawDescData)
	})
	return file_constraint_proto_rawDescData
}

var file_constraint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_constraint_proto_goTypes = []interface{}{
	(ConstraintType)(0),     // 0: types.ConstraintType
	(MagicConstant)(0),      // 1: types.MagicConstant
	(*RangeValue)(nil),      // 2: types.RangeValue
	(*WhitelistValues)(nil), // 3: types.WhitelistValues
	(*Constraint)(nil),      // 4: types.Constraint
}
var file_constraint_proto_depIdxs = []int32{
	0, // 0: types.Constraint.type:type_name -> types.ConstraintType
	2, // 1: types.Constraint.range_value:type_name -> types.RangeValue
	3, // 2: types.Constraint.whitelist_values:type_name -> types.WhitelistValues
	1, // 3: types.Constraint.magic_constant_value:type_name -> types.MagicConstant
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_constraint_proto_init() }
func file_constraint_proto_init() {
	if File_constraint_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_constraint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RangeValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WhitelistValues); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_constraint_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Constraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_constraint_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*Constraint_FixedValue)(nil),
		(*Constraint_MaxValue)(nil),
		(*Constraint_MinValue)(nil),
		(*Constraint_RangeValue)(nil),
		(*Constraint_WhitelistValues)(nil),
		(*Constraint_MaxPerPeriodValue)(nil),
		(*Constraint_MagicConstantValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_constraint_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constraint_proto_goTypes,
		DependencyIndexes: file_constraint_proto_depIdxs,
		EnumInfos:         file_constraint_proto_enumTypes,
		MessageInfos:      file_constraint_proto_msgTypes,
	}.Build()
	File_constraint_proto = out.File
	file_constraint_proto_rawDesc = nil
	file_constraint_proto_goTypes = nil
	file_constraint_proto_depIdxs = nil
}
