// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: constraint.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConstraintType defines the type of constraint
type ConstraintType int32

const (
	ConstraintType_CONSTRAINT_TYPE_UNSPECIFIED    ConstraintType = 0
	ConstraintType_CONSTRAINT_TYPE_FIXED          ConstraintType = 1
	ConstraintType_CONSTRAINT_TYPE_MAX            ConstraintType = 2
	ConstraintType_CONSTRAINT_TYPE_MIN            ConstraintType = 3
	ConstraintType_CONSTRAINT_TYPE_MAGIC_CONSTANT ConstraintType = 4
	ConstraintType_CONSTRAINT_TYPE_ANY            ConstraintType = 5
	ConstraintType_CONSTRAINT_TYPE_REGEXP         ConstraintType = 6
)

// Enum value maps for ConstraintType.
var (
	ConstraintType_name = map[int32]string{
		0: "CONSTRAINT_TYPE_UNSPECIFIED",
		1: "CONSTRAINT_TYPE_FIXED",
		2: "CONSTRAINT_TYPE_MAX",
		3: "CONSTRAINT_TYPE_MIN",
		4: "CONSTRAINT_TYPE_MAGIC_CONSTANT",
		5: "CONSTRAINT_TYPE_ANY",
		6: "CONSTRAINT_TYPE_REGEXP",
	}
	ConstraintType_value = map[string]int32{
		"CONSTRAINT_TYPE_UNSPECIFIED":    0,
		"CONSTRAINT_TYPE_FIXED":          1,
		"CONSTRAINT_TYPE_MAX":            2,
		"CONSTRAINT_TYPE_MIN":            3,
		"CONSTRAINT_TYPE_MAGIC_CONSTANT": 4,
		"CONSTRAINT_TYPE_ANY":            5,
		"CONSTRAINT_TYPE_REGEXP":         6,
	}
)

func (x ConstraintType) Enum() *ConstraintType {
	p := new(ConstraintType)
	*p = x
	return p
}

func (x ConstraintType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConstraintType) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[0].Descriptor()
}

func (ConstraintType) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[0]
}

func (x ConstraintType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConstraintType.Descriptor instead.
func (ConstraintType) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0}
}

type MagicConstant int32

const (
	MagicConstant_UNSPECIFIED       MagicConstant = 0
	MagicConstant_VULTISIG_TREASURY MagicConstant = 1
	MagicConstant_THORCHAIN_VAULT   MagicConstant = 2
	MagicConstant_THORCHAIN_ROUTER  MagicConstant = 3
	MagicConstant_MAYACHAIN_VAULT   MagicConstant = 4
)

// Enum value maps for MagicConstant.
var (
	MagicConstant_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "VULTISIG_TREASURY",
		2: "THORCHAIN_VAULT",
		3: "THORCHAIN_ROUTER",
		4: "MAYACHAIN_VAULT",
	}
	MagicConstant_value = map[string]int32{
		"UNSPECIFIED":       0,
		"VULTISIG_TREASURY": 1,
		"THORCHAIN_VAULT":   2,
		"THORCHAIN_ROUTER":  3,
		"MAYACHAIN_VAULT":   4,
	}
)

func (x MagicConstant) Enum() *MagicConstant {
	p := new(MagicConstant)
	*p = x
	return p
}

func (x MagicConstant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MagicConstant) Descriptor() protoreflect.EnumDescriptor {
	return file_constraint_proto_enumTypes[1].Descriptor()
}

func (MagicConstant) Type() protoreflect.EnumType {
	return &file_constraint_proto_enumTypes[1]
}

func (x MagicConstant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MagicConstant.Descriptor instead.
func (MagicConstant) EnumDescriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{1}
}

// Constraint defines restrictions on a parameter
type Constraint struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of constraint (fixed, max, min, etc.)
	Type ConstraintType `protobuf:"varint,1,opt,name=type,proto3,enum=types.ConstraintType" json:"type,omitempty"`
	// Value of the constraint (depends on Type)
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Constraint_FixedValue
	//	*Constraint_MaxValue
	//	*Constraint_MinValue
	//	*Constraint_MagicConstantValue
	//	*Constraint_RegexpValue
	Value isConstraint_Value `protobuf_oneof:"value"`
	// Additional metadata for the constraint
	DenominatedIn string `protobuf:"bytes,6,opt,name=denominated_in,json=denominatedIn,proto3" json:"denominated_in,omitempty"`
	Period        string `protobuf:"bytes,7,opt,name=period,proto3" json:"period,omitempty"`
	Required      bool   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Constraint) Reset() {
	*x = Constraint{}
	mi := &file_constraint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Constraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Constraint) ProtoMessage() {}

func (x *Constraint) ProtoReflect() protoreflect.Message {
	mi := &file_constraint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Constraint.ProtoReflect.Descriptor instead.
func (*Constraint) Descriptor() ([]byte, []int) {
	return file_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *Constraint) GetType() ConstraintType {
	if x != nil {
		return x.Type
	}
	return ConstraintType_CONSTRAINT_TYPE_UNSPECIFIED
}

func (x *Constraint) GetValue() isConstraint_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Constraint) GetFixedValue() string {
	if x != nil {
		if x, ok := x.Value.(*Constraint_FixedValue); ok {
			return x.FixedValue
		}
	}
	return ""
}

func (x *Constraint) GetMaxValue() string {
	if x != nil {
		if x, ok := x.Value.(*Constraint_MaxValue); ok {
			return x.MaxValue
		}
	}
	return ""
}

func (x *Constraint) GetMinValue() string {
	if x != nil {
		if x, ok := x.Value.(*Constraint_MinValue); ok {
			return x.MinValue
		}
	}
	return ""
}

func (x *Constraint) GetMagicConstantValue() MagicConstant {
	if x != nil {
		if x, ok := x.Value.(*Constraint_MagicConstantValue); ok {
			return x.MagicConstantValue
		}
	}
	return MagicConstant_UNSPECIFIED
}

func (x *Constraint) GetRegexpValue() string {
	if x != nil {
		if x, ok := x.Value.(*Constraint_RegexpValue); ok {
			return x.RegexpValue
		}
	}
	return ""
}

func (x *Constraint) GetDenominatedIn() string {
	if x != nil {
		return x.DenominatedIn
	}
	return ""
}

func (x *Constraint) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *Constraint) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

type isConstraint_Value interface {
	isConstraint_Value()
}

type Constraint_FixedValue struct {
	FixedValue string `protobuf:"bytes,2,opt,name=fixed_value,json=fixedValue,proto3,oneof"`
}

type Constraint_MaxValue struct {
	MaxValue string `protobuf:"bytes,3,opt,name=max_value,json=maxValue,proto3,oneof"`
}

type Constraint_MinValue struct {
	MinValue string `protobuf:"bytes,4,opt,name=min_value,json=minValue,proto3,oneof"`
}

type Constraint_MagicConstantValue struct {
	MagicConstantValue MagicConstant `protobuf:"varint,5,opt,name=magic_constant_value,json=magicConstantValue,proto3,enum=types.MagicConstant,oneof"`
}

type Constraint_RegexpValue struct {
	RegexpValue string `protobuf:"bytes,9,opt,name=regexp_value,json=regexpValue,proto3,oneof"`
}

func (*Constraint_FixedValue) isConstraint_Value() {}

func (*Constraint_MaxValue) isConstraint_Value() {}

func (*Constraint_MinValue) isConstraint_Value() {}

func (*Constraint_MagicConstantValue) isConstraint_Value() {}

func (*Constraint_RegexpValue) isConstraint_Value() {}

var File_constraint_proto protoreflect.FileDescriptor

const file_constraint_proto_rawDesc = "" +
	"\n" +
	"\x10constraint.proto\x12\x05types\"\xeb\x02\n" +
	"\n" +
	"Constraint\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.types.ConstraintTypeR\x04type\x12!\n" +
	"\vfixed_value\x18\x02 \x01(\tH\x00R\n" +
	"fixedValue\x12\x1d\n" +
	"\tmax_value\x18\x03 \x01(\tH\x00R\bmaxValue\x12\x1d\n" +
	"\tmin_value\x18\x04 \x01(\tH\x00R\bminValue\x12H\n" +
	"\x14magic_constant_value\x18\x05 \x01(\x0e2\x14.types.MagicConstantH\x00R\x12magicConstantValue\x12#\n" +
	"\fregexp_value\x18\t \x01(\tH\x00R\vregexpValue\x12%\n" +
	"\x0edenominated_in\x18\x06 \x01(\tR\rdenominatedIn\x12\x16\n" +
	"\x06period\x18\a \x01(\tR\x06period\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequiredB\a\n" +
	"\x05value*\xd7\x01\n" +
	"\x0eConstraintType\x12\x1f\n" +
	"\x1bCONSTRAINT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CONSTRAINT_TYPE_FIXED\x10\x01\x12\x17\n" +
	"\x13CONSTRAINT_TYPE_MAX\x10\x02\x12\x17\n" +
	"\x13CONSTRAINT_TYPE_MIN\x10\x03\x12\"\n" +
	"\x1eCONSTRAINT_TYPE_MAGIC_CONSTANT\x10\x04\x12\x17\n" +
	"\x13CONSTRAINT_TYPE_ANY\x10\x05\x12\x1a\n" +
	"\x16CONSTRAINT_TYPE_REGEXP\x10\x06*w\n" +
	"\rMagicConstant\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11VULTISIG_TREASURY\x10\x01\x12\x13\n" +
	"\x0fTHORCHAIN_VAULT\x10\x02\x12\x14\n" +
	"\x10THORCHAIN_ROUTER\x10\x03\x12\x13\n" +
	"\x0fMAYACHAIN_VAULT\x10\x04B#Z!github.com/vultisig/recipes/typesb\x06proto3"

var (
	file_constraint_proto_rawDescOnce sync.Once
	file_constraint_proto_rawDescData []byte
)

func file_constraint_proto_rawDescGZIP() []byte {
	file_constraint_proto_rawDescOnce.Do(func() {
		file_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_constraint_proto_rawDesc), len(file_constraint_proto_rawDesc)))
	})
	return file_constraint_proto_rawDescData
}

var file_constraint_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_constraint_proto_goTypes = []any{
	(ConstraintType)(0), // 0: types.ConstraintType
	(MagicConstant)(0),  // 1: types.MagicConstant
	(*Constraint)(nil),  // 2: types.Constraint
}
var file_constraint_proto_depIdxs = []int32{
	0, // 0: types.Constraint.type:type_name -> types.ConstraintType
	1, // 1: types.Constraint.magic_constant_value:type_name -> types.MagicConstant
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_constraint_proto_init() }
func file_constraint_proto_init() {
	if File_constraint_proto != nil {
		return
	}
	file_constraint_proto_msgTypes[0].OneofWrappers = []any{
		(*Constraint_FixedValue)(nil),
		(*Constraint_MaxValue)(nil),
		(*Constraint_MinValue)(nil),
		(*Constraint_MagicConstantValue)(nil),
		(*Constraint_RegexpValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_constraint_proto_rawDesc), len(file_constraint_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_constraint_proto_goTypes,
		DependencyIndexes: file_constraint_proto_depIdxs,
		EnumInfos:         file_constraint_proto_enumTypes,
		MessageInfos:      file_constraint_proto_msgTypes,
	}.Build()
	File_constraint_proto = out.File
	file_constraint_proto_goTypes = nil
	file_constraint_proto_depIdxs = nil
}
