// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.21.5
// source: parameter_constraint.proto

package types

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ParameterConstraint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ParameterName string      `protobuf:"bytes,1,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	Constraint    *Constraint `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
}

func (x *ParameterConstraint) Reset() {
	*x = ParameterConstraint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_parameter_constraint_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterConstraint) ProtoMessage() {}

func (x *ParameterConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_parameter_constraint_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterConstraint.ProtoReflect.Descriptor instead.
func (*ParameterConstraint) Descriptor() ([]byte, []int) {
	return file_parameter_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *ParameterConstraint) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

func (x *ParameterConstraint) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

var File_parameter_constraint_proto protoreflect.FileDescriptor

var file_parameter_constraint_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x1a, 0x10, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6f, 0x0a, 0x13, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x43, 0x6f, 0x6e, 0x73, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x73,
	0x74, 0x72, 0x61, 0x69, 0x6e, 0x74, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x74, 0x69, 0x73, 0x69, 0x67, 0x2f, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_parameter_constraint_proto_rawDescOnce sync.Once
	file_parameter_constraint_proto_rawDescData = file_parameter_constraint_proto_rawDesc
)

func file_parameter_constraint_proto_rawDescGZIP() []byte {
	file_parameter_constraint_proto_rawDescOnce.Do(func() {
		file_parameter_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(file_parameter_constraint_proto_rawDescData)
	})
	return file_parameter_constraint_proto_rawDescData
}

var file_parameter_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameter_constraint_proto_goTypes = []interface{}{
	(*ParameterConstraint)(nil), // 0: types.ParameterConstraint
	(*Constraint)(nil),          // 1: types.Constraint
}
var file_parameter_constraint_proto_depIdxs = []int32{
	1, // 0: types.ParameterConstraint.constraint:type_name -> types.Constraint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_parameter_constraint_proto_init() }
func file_parameter_constraint_proto_init() {
	if File_parameter_constraint_proto != nil {
		return
	}
	file_constraint_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_parameter_constraint_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterConstraint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_parameter_constraint_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameter_constraint_proto_goTypes,
		DependencyIndexes: file_parameter_constraint_proto_depIdxs,
		MessageInfos:      file_parameter_constraint_proto_msgTypes,
	}.Build()
	File_parameter_constraint_proto = out.File
	file_parameter_constraint_proto_rawDesc = nil
	file_parameter_constraint_proto_goTypes = nil
	file_parameter_constraint_proto_depIdxs = nil
}
