// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: parameter_constraint.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParameterConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParameterName string                 `protobuf:"bytes,1,opt,name=parameter_name,json=parameterName,proto3" json:"parameter_name,omitempty"`
	Constraint    *Constraint            `protobuf:"bytes,2,opt,name=constraint,proto3" json:"constraint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterConstraint) Reset() {
	*x = ParameterConstraint{}
	mi := &file_parameter_constraint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterConstraint) ProtoMessage() {}

func (x *ParameterConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_parameter_constraint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterConstraint.ProtoReflect.Descriptor instead.
func (*ParameterConstraint) Descriptor() ([]byte, []int) {
	return file_parameter_constraint_proto_rawDescGZIP(), []int{0}
}

func (x *ParameterConstraint) GetParameterName() string {
	if x != nil {
		return x.ParameterName
	}
	return ""
}

func (x *ParameterConstraint) GetConstraint() *Constraint {
	if x != nil {
		return x.Constraint
	}
	return nil
}

var File_parameter_constraint_proto protoreflect.FileDescriptor

const file_parameter_constraint_proto_rawDesc = "" +
	"\n" +
	"\x1aparameter_constraint.proto\x12\x05types\x1a\x10constraint.proto\"o\n" +
	"\x13ParameterConstraint\x12%\n" +
	"\x0eparameter_name\x18\x01 \x01(\tR\rparameterName\x121\n" +
	"\n" +
	"constraint\x18\x02 \x01(\v2\x11.types.ConstraintR\n" +
	"constraintB#Z!github.com/vultisig/recipes/typesb\x06proto3"

var (
	file_parameter_constraint_proto_rawDescOnce sync.Once
	file_parameter_constraint_proto_rawDescData []byte
)

func file_parameter_constraint_proto_rawDescGZIP() []byte {
	file_parameter_constraint_proto_rawDescOnce.Do(func() {
		file_parameter_constraint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_parameter_constraint_proto_rawDesc), len(file_parameter_constraint_proto_rawDesc)))
	})
	return file_parameter_constraint_proto_rawDescData
}

var file_parameter_constraint_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_parameter_constraint_proto_goTypes = []any{
	(*ParameterConstraint)(nil), // 0: types.ParameterConstraint
	(*Constraint)(nil),          // 1: types.Constraint
}
var file_parameter_constraint_proto_depIdxs = []int32{
	1, // 0: types.ParameterConstraint.constraint:type_name -> types.Constraint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_parameter_constraint_proto_init() }
func file_parameter_constraint_proto_init() {
	if File_parameter_constraint_proto != nil {
		return
	}
	file_constraint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_parameter_constraint_proto_rawDesc), len(file_parameter_constraint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_parameter_constraint_proto_goTypes,
		DependencyIndexes: file_parameter_constraint_proto_depIdxs,
		MessageInfos:      file_parameter_constraint_proto_msgTypes,
	}.Build()
	File_parameter_constraint_proto = out.File
	file_parameter_constraint_proto_goTypes = nil
	file_parameter_constraint_proto_depIdxs = nil
}
