// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: recipe_template.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecipeTemplate provides example policy configurations for developers
// This allows plugin developers to showcase different use cases and configurations
type RecipeTemplate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for this template
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable title for the template
	Title string `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	// Detailed description of what this template does
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// The example policy payload that demonstrates this template
	PolicyPayload *Policy `protobuf:"bytes,4,opt,name=policy_payload,json=policyPayload,proto3" json:"policy_payload,omitempty"`
	// Optional tags for categorizing templates
	Tags          []string `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeTemplate) Reset() {
	*x = RecipeTemplate{}
	mi := &file_recipe_template_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeTemplate) ProtoMessage() {}

func (x *RecipeTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_template_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeTemplate.ProtoReflect.Descriptor instead.
func (*RecipeTemplate) Descriptor() ([]byte, []int) {
	return file_recipe_template_proto_rawDescGZIP(), []int{0}
}

func (x *RecipeTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecipeTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RecipeTemplate) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RecipeTemplate) GetPolicyPayload() *Policy {
	if x != nil {
		return x.PolicyPayload
	}
	return nil
}

func (x *RecipeTemplate) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// Collection of recipe templates for a plugin
type RecipeTemplateCollection struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Plugin identification
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// Collection of templates provided by this plugin
	Templates     []*RecipeTemplate `protobuf:"bytes,2,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecipeTemplateCollection) Reset() {
	*x = RecipeTemplateCollection{}
	mi := &file_recipe_template_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecipeTemplateCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecipeTemplateCollection) ProtoMessage() {}

func (x *RecipeTemplateCollection) ProtoReflect() protoreflect.Message {
	mi := &file_recipe_template_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecipeTemplateCollection.ProtoReflect.Descriptor instead.
func (*RecipeTemplateCollection) Descriptor() ([]byte, []int) {
	return file_recipe_template_proto_rawDescGZIP(), []int{1}
}

func (x *RecipeTemplateCollection) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RecipeTemplateCollection) GetTemplates() []*RecipeTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

var File_recipe_template_proto protoreflect.FileDescriptor

const file_recipe_template_proto_rawDesc = "" +
	"\n" +
	"\x15recipe_template.proto\x12\x05types\x1a\fpolicy.proto\"\xa2\x01\n" +
	"\x0eRecipeTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x124\n" +
	"\x0epolicy_payload\x18\x04 \x01(\v2\r.types.PolicyR\rpolicyPayload\x12\x12\n" +
	"\x04tags\x18\x05 \x03(\tR\x04tags\"l\n" +
	"\x18RecipeTemplateCollection\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x123\n" +
	"\ttemplates\x18\x02 \x03(\v2\x15.types.RecipeTemplateR\ttemplatesB#Z!github.com/vultisig/recipes/typesb\x06proto3"

var (
	file_recipe_template_proto_rawDescOnce sync.Once
	file_recipe_template_proto_rawDescData []byte
)

func file_recipe_template_proto_rawDescGZIP() []byte {
	file_recipe_template_proto_rawDescOnce.Do(func() {
		file_recipe_template_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recipe_template_proto_rawDesc), len(file_recipe_template_proto_rawDesc)))
	})
	return file_recipe_template_proto_rawDescData
}

var file_recipe_template_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recipe_template_proto_goTypes = []any{
	(*RecipeTemplate)(nil),           // 0: types.RecipeTemplate
	(*RecipeTemplateCollection)(nil), // 1: types.RecipeTemplateCollection
	(*Policy)(nil),                   // 2: types.Policy
}
var file_recipe_template_proto_depIdxs = []int32{
	2, // 0: types.RecipeTemplate.policy_payload:type_name -> types.Policy
	0, // 1: types.RecipeTemplateCollection.templates:type_name -> types.RecipeTemplate
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_recipe_template_proto_init() }
func file_recipe_template_proto_init() {
	if File_recipe_template_proto != nil {
		return
	}
	file_policy_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recipe_template_proto_rawDesc), len(file_recipe_template_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_recipe_template_proto_goTypes,
		DependencyIndexes: file_recipe_template_proto_depIdxs,
		MessageInfos:      file_recipe_template_proto_msgTypes,
	}.Build()
	File_recipe_template_proto = out.File
	file_recipe_template_proto_goTypes = nil
	file_recipe_template_proto_depIdxs = nil
}
