// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rule.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Effect determines whether a rule allows or denies access
type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED Effect = 0
	Effect_EFFECT_ALLOW       Effect = 1
	Effect_EFFECT_DENY        Effect = 2
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_ALLOW",
		2: "EFFECT_DENY",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED": 0,
		"EFFECT_ALLOW":       1,
		"EFFECT_DENY":        2,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_rule_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_rule_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{0}
}

// Rule represents a single permission rule in the policy
type Rule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource specifies what resource this rule applies to
	Resource string `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// Effect determines whether the rule allows or denies access
	Effect Effect `protobuf:"varint,2,opt,name=effect,proto3,enum=types.Effect" json:"effect,omitempty"`
	// Description provides human-readable details about this rule
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Constraints defines restrictions on the resource
	Constraints map[string]*Constraint `protobuf:"bytes,4,rep,name=constraints,proto3" json:"constraints,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Authorization defines how this should be authorized (if needed)
	Authorization *Authorization `protobuf:"bytes,5,opt,name=authorization,proto3" json:"authorization,omitempty"`
	// Rule ID
	Id string `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	// Parameter constraints
	ParameterConstraints []*ParameterConstraint `protobuf:"bytes,7,rep,name=parameter_constraints,json=parameterConstraints,proto3" json:"parameter_constraints,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Rule) Reset() {
	*x = Rule{}
	mi := &file_rule_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rule) ProtoMessage() {}

func (x *Rule) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rule.ProtoReflect.Descriptor instead.
func (*Rule) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{0}
}

func (x *Rule) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *Rule) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

func (x *Rule) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Rule) GetConstraints() map[string]*Constraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

func (x *Rule) GetAuthorization() *Authorization {
	if x != nil {
		return x.Authorization
	}
	return nil
}

func (x *Rule) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Rule) GetParameterConstraints() []*ParameterConstraint {
	if x != nil {
		return x.ParameterConstraints
	}
	return nil
}

// Authorization represents how a transaction should be authorized
type Authorization struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type of authorization (prompt, allow, deny)
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Message to display when prompting the user
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authorization) Reset() {
	*x = Authorization{}
	mi := &file_rule_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authorization) ProtoMessage() {}

func (x *Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_rule_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authorization.ProtoReflect.Descriptor instead.
func (*Authorization) Descriptor() ([]byte, []int) {
	return file_rule_proto_rawDescGZIP(), []int{1}
}

func (x *Authorization) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Authorization) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_rule_proto protoreflect.FileDescriptor

const file_rule_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rule.proto\x12\x05types\x1a\x10constraint.proto\x1a\x1aparameter_constraint.proto\"\x9b\x03\n" +
	"\x04Rule\x12\x1a\n" +
	"\bresource\x18\x01 \x01(\tR\bresource\x12%\n" +
	"\x06effect\x18\x02 \x01(\x0e2\r.types.EffectR\x06effect\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12>\n" +
	"\vconstraints\x18\x04 \x03(\v2\x1c.types.Rule.ConstraintsEntryR\vconstraints\x12:\n" +
	"\rauthorization\x18\x05 \x01(\v2\x14.types.AuthorizationR\rauthorization\x12\x0e\n" +
	"\x02id\x18\x06 \x01(\tR\x02id\x12O\n" +
	"\x15parameter_constraints\x18\a \x03(\v2\x1a.types.ParameterConstraintR\x14parameterConstraints\x1aQ\n" +
	"\x10ConstraintsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.types.ConstraintR\x05value:\x028\x01\"=\n" +
	"\rAuthorization\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*C\n" +
	"\x06Effect\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fEFFECT_ALLOW\x10\x01\x12\x0f\n" +
	"\vEFFECT_DENY\x10\x02B#Z!github.com/vultisig/recipes/typesb\x06proto3"

var (
	file_rule_proto_rawDescOnce sync.Once
	file_rule_proto_rawDescData []byte
)

func file_rule_proto_rawDescGZIP() []byte {
	file_rule_proto_rawDescOnce.Do(func() {
		file_rule_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rule_proto_rawDesc), len(file_rule_proto_rawDesc)))
	})
	return file_rule_proto_rawDescData
}

var file_rule_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rule_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rule_proto_goTypes = []any{
	(Effect)(0),                 // 0: types.Effect
	(*Rule)(nil),                // 1: types.Rule
	(*Authorization)(nil),       // 2: types.Authorization
	nil,                         // 3: types.Rule.ConstraintsEntry
	(*ParameterConstraint)(nil), // 4: types.ParameterConstraint
	(*Constraint)(nil),          // 5: types.Constraint
}
var file_rule_proto_depIdxs = []int32{
	0, // 0: types.Rule.effect:type_name -> types.Effect
	3, // 1: types.Rule.constraints:type_name -> types.Rule.ConstraintsEntry
	2, // 2: types.Rule.authorization:type_name -> types.Authorization
	4, // 3: types.Rule.parameter_constraints:type_name -> types.ParameterConstraint
	5, // 4: types.Rule.ConstraintsEntry.value:type_name -> types.Constraint
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_rule_proto_init() }
func file_rule_proto_init() {
	if File_rule_proto != nil {
		return
	}
	file_constraint_proto_init()
	file_parameter_constraint_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rule_proto_rawDesc), len(file_rule_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rule_proto_goTypes,
		DependencyIndexes: file_rule_proto_depIdxs,
		EnumInfos:         file_rule_proto_enumTypes,
		MessageInfos:      file_rule_proto_msgTypes,
	}.Build()
	File_rule_proto = out.File
	file_rule_proto_goTypes = nil
	file_rule_proto_depIdxs = nil
}
