// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: thorchain.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Asset represents a THORChain asset identifier
type Asset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         string                 `protobuf:"bytes,1,opt,name=chain,proto3" json:"chain,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Ticker        string                 `protobuf:"bytes,3,opt,name=ticker,proto3" json:"ticker,omitempty"`
	Synth         bool                   `protobuf:"varint,4,opt,name=synth,proto3" json:"synth,omitempty"`
	Trade         bool                   `protobuf:"varint,5,opt,name=trade,proto3" json:"trade,omitempty"`
	Secured       bool                   `protobuf:"varint,6,opt,name=secured,proto3" json:"secured,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Asset) Reset() {
	*x = Asset{}
	mi := &file_thorchain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Asset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Asset) ProtoMessage() {}

func (x *Asset) ProtoReflect() protoreflect.Message {
	mi := &file_thorchain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Asset.ProtoReflect.Descriptor instead.
func (*Asset) Descriptor() ([]byte, []int) {
	return file_thorchain_proto_rawDescGZIP(), []int{0}
}

func (x *Asset) GetChain() string {
	if x != nil {
		return x.Chain
	}
	return ""
}

func (x *Asset) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Asset) GetTicker() string {
	if x != nil {
		return x.Ticker
	}
	return ""
}

func (x *Asset) GetSynth() bool {
	if x != nil {
		return x.Synth
	}
	return false
}

func (x *Asset) GetTrade() bool {
	if x != nil {
		return x.Trade
	}
	return false
}

func (x *Asset) GetSecured() bool {
	if x != nil {
		return x.Secured
	}
	return false
}

// Coin represents a token with denomination and amount (matching common.Coin)
type Coin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asset         *Asset                 `protobuf:"bytes,1,opt,name=asset,proto3" json:"asset,omitempty"`
	Amount        string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Decimals      int64                  `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coin) Reset() {
	*x = Coin{}
	mi := &file_thorchain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coin) ProtoMessage() {}

func (x *Coin) ProtoReflect() protoreflect.Message {
	mi := &file_thorchain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coin.ProtoReflect.Descriptor instead.
func (*Coin) Descriptor() ([]byte, []int) {
	return file_thorchain_proto_rawDescGZIP(), []int{1}
}

func (x *Coin) GetAsset() *Asset {
	if x != nil {
		return x.Asset
	}
	return nil
}

func (x *Coin) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *Coin) GetDecimals() int64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

// MsgDeposit represents THORChain's MsgDeposit message for swaps/deposits
type MsgDeposit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Coins being deposited
	Coins []*Coin `protobuf:"bytes,1,rep,name=coins,proto3" json:"coins,omitempty"`
	// Memo contains swap instructions including destination address
	Memo string `protobuf:"bytes,2,opt,name=memo,proto3" json:"memo,omitempty"`
	// Signer is the address of the depositor (as bytes for bech32 compatibility)
	Signer        []byte `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgDeposit) Reset() {
	*x = MsgDeposit{}
	mi := &file_thorchain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgDeposit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgDeposit) ProtoMessage() {}

func (x *MsgDeposit) ProtoReflect() protoreflect.Message {
	mi := &file_thorchain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgDeposit.ProtoReflect.Descriptor instead.
func (*MsgDeposit) Descriptor() ([]byte, []int) {
	return file_thorchain_proto_rawDescGZIP(), []int{2}
}

func (x *MsgDeposit) GetCoins() []*Coin {
	if x != nil {
		return x.Coins
	}
	return nil
}

func (x *MsgDeposit) GetMemo() string {
	if x != nil {
		return x.Memo
	}
	return ""
}

func (x *MsgDeposit) GetSigner() []byte {
	if x != nil {
		return x.Signer
	}
	return nil
}

var File_thorchain_proto protoreflect.FileDescriptor

const file_thorchain_proto_rawDesc = "" +
	"\n" +
	"\x0fthorchain.proto\x12\x05types\"\x93\x01\n" +
	"\x05Asset\x12\x14\n" +
	"\x05chain\x18\x01 \x01(\tR\x05chain\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x16\n" +
	"\x06ticker\x18\x03 \x01(\tR\x06ticker\x12\x14\n" +
	"\x05synth\x18\x04 \x01(\bR\x05synth\x12\x14\n" +
	"\x05trade\x18\x05 \x01(\bR\x05trade\x12\x18\n" +
	"\asecured\x18\x06 \x01(\bR\asecured\"^\n" +
	"\x04Coin\x12\"\n" +
	"\x05asset\x18\x01 \x01(\v2\f.types.AssetR\x05asset\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\x03R\bdecimals\"[\n" +
	"\n" +
	"MsgDeposit\x12!\n" +
	"\x05coins\x18\x01 \x03(\v2\v.types.CoinR\x05coins\x12\x12\n" +
	"\x04memo\x18\x02 \x01(\tR\x04memo\x12\x16\n" +
	"\x06signer\x18\x03 \x01(\fR\x06signerB#Z!github.com/vultisig/recipes/typesb\x06proto3"

var (
	file_thorchain_proto_rawDescOnce sync.Once
	file_thorchain_proto_rawDescData []byte
)

func file_thorchain_proto_rawDescGZIP() []byte {
	file_thorchain_proto_rawDescOnce.Do(func() {
		file_thorchain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_thorchain_proto_rawDesc), len(file_thorchain_proto_rawDesc)))
	})
	return file_thorchain_proto_rawDescData
}

var file_thorchain_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_thorchain_proto_goTypes = []any{
	(*Asset)(nil),      // 0: types.Asset
	(*Coin)(nil),       // 1: types.Coin
	(*MsgDeposit)(nil), // 2: types.MsgDeposit
}
var file_thorchain_proto_depIdxs = []int32{
	0, // 0: types.Coin.asset:type_name -> types.Asset
	1, // 1: types.MsgDeposit.coins:type_name -> types.Coin
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_thorchain_proto_init() }
func file_thorchain_proto_init() {
	if File_thorchain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_thorchain_proto_rawDesc), len(file_thorchain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thorchain_proto_goTypes,
		DependencyIndexes: file_thorchain_proto_depIdxs,
		MessageInfos:      file_thorchain_proto_msgTypes,
	}.Build()
	File_thorchain_proto = out.File
	file_thorchain_proto_goTypes = nil
	file_thorchain_proto_depIdxs = nil
}
